### ISSUE TITLE
More issues due to lack of maitenance! Can someone help, please?

### ISSUE THREAD

**Issue by marcospg75** [asev/homeassistant-uponor#44]
Can some one with the right skills take care of this integration... now I get new errors from HA...

No se pudo llamar al servicio climate/set_temperature. Detected that custom integration 'uponor' calls async_dispatcher_send from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_dispatcher_send at custom_components/uponor/__init__.py, line 156: async_dispatcher_send(self._hass, SIGNAL_UPONOR_STATE_UPDATE). Please report it to the author of the 'uponor' custom integration.

Thank you!

**Comment by lucius-the** [comment]
Coming here with the same issue. Yes, it seems that asev is missing. There are two pull requests from January and February without any comments from asev, which is strange. I hope the guy is just busy but otherwise ok.

I agree it would be nice if someone could fork and take over further maintenance. This is a very valuable integration, but needs some maintenance obviously, as Home Assistant changes things. However I have no idea how to take over or where to start from. I am a developer but very unfamiliar with Python, Github and Home Asssistant. Those two persons that sent pull requests... They likely know enough to be able to take over...

Of course, it would be correct to try and contact asev first. But I think he's gone... GitHub at least hasn't seen him in years.

**Comment by Martijnvanoijen** [comment]
Same issue here :-). Comment to follow

**Comment by Icegames-dk** [comment]
Same issue here:
Kunne ikke kalde tjenesten climate/set_temperature. Detected that custom integration 'uponor' calls async_dispatcher_send from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_dispatcher_send at custom_components/uponor/__init__.py, line 156: async_dispatcher_send(self._hass, SIGNAL_UPONOR_STATE_UPDATE). Please report it to the author of the 'uponor' custom integration.

Core
2024.6.2
Supervisor
2024.06.1
Operating System
12.3
Brugerflade
20240610.0

**Comment by gekkekoe** [comment]
edit __init__.py at line 14 to
`from homeassistant.helpers.dispatcher import dispatcher_send as async_dispatcher_send`
reboot HA and it should work again.

**Comment by dave-code-ruiz** [comment]
Fork that solves most issues in this integration:

https://github.com/asev/homeassistant-uponor/issues/46
